In [1]:
import pandas as pd
import numpy as np

In [4]:
data=pd.read_csv("Dataset\country_wise_latest.csv")

In [5]:
data.head(10)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe
2,Algeria,27973,1163,18837,7973,616,8,749,4.16,67.34,6.17,23691,4282,18.07,Africa
3,Andorra,907,52,803,52,10,0,0,5.73,88.53,6.48,884,23,2.60,Europe
4,Angola,950,41,242,667,18,1,0,4.32,25.47,16.94,749,201,26.84,Africa
5,Antigua and Barbuda,86,3,65,18,4,0,5,3.49,75.58,4.62,76,10,13.16,Americas
6,Argentina,167416,3059,72575,91782,4890,120,2057,1.83,43.35,4.21,130774,36642,28.02,Americas
7,Armenia,37390,711,26665,10014,73,6,187,1.90,71.32,2.67,34981,2409,6.89,Europe
8,Australia,15303,167,9311,5825,368,6,137,1.09,60.84,1.79,12428,2875,23.13,Western Pacific
9,Austria,20558,713,18246,1599,86,1,37,3.47,88.75,3.91,19743,815,4.13,Europe

In [8]:
data.isnull().sum()

Country/Region            0
Confirmed                 0
Deaths                    0
Recovered                 0
Active                    0
New cases                 0
New deaths                0
New recovered             0
Deaths / 100 Cases        0
Recovered / 100 Cases     0
Deaths / 100 Recovered    0
Confirmed last week       0
1 week change             0
1 week % increase         0
WHO Region                0
dtype: int64

In [9]:
data.describe()

,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase
count,1.870000e+02,187.000000,1.870000e+02,1.870000e+02,187.000000,187.000000,187.000000,187.000000,187.000000,187.00,1.870000e+02,187.000000,187.000000
mean,8.813094e+04,3497.518717,5.063148e+04,3.400194e+04,1222.957219,28.957219,933.812834,3.019519,64.820535,inf,7.868248e+04,9448.459893,13.606203
std,3.833187e+05,14100.002482,1.901882e+05,2.133262e+05,5710.374790,120.037173,4197.719635,3.454302,26.287694,NaN,3.382737e+05,47491.127684,24.509838
min,1.000000e+01,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,1.000000e+01,-47.000000,-3.840000
25%,1.114000e+03,18.500000,6.265000e+02,1.415000e+02,4.000000,0.000000,0.000000,0.945000,48.770000,1.45,1.051500e+03,49.000000,2.775000
50%,5.059000e+03,108.000000,2.815000e+03,1.600000e+03,49.000000,1.000000,22.000000,2.150000,71.320000,3.62,5.020000e+03,432.000000,6.890000
75%,4.046050e+04,734.000000,2.260600e+04,9.149000e+03,419.500000,6.000000,221.000000,3.875000,86.885000,6.44,3.708050e+04,3172.000000,16.855000
max,4.290259e+06,148011.000000,1.846641e+06,2.816444e+06,56336.000000,1076.000000,33728.000000,28.560000,100.000000,inf,3.834677e+06,455582.000000,226.320000

In [10]:
data.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
182    False
183    False
184    False
185    False
186    False
Length: 187, dtype: bool

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 187 entries, 0 to 186
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Country/Region          187 non-null    object
 1   Confirmed               187 non-null    int64
 2   Deaths                  187 non-null    int64
 3   Recovered               187 non-null    int64
 4   Active                  187 non-null    int64
 5   New cases               187 non-null    int64
 6   New deaths              187 non-null    int64
 7   New recovered           187 non-null    int64
 8   Deaths / 100 Cases      187 non-null    float64
 9   Recovered / 100 Cases   187 non-null    float64
 10  Deaths / 100 Recovered  187 non-null    float64
 11  Confirmed last week     187 non-null    int64
 12  1 week change           187 non-null    int64
 13  1 week % increase       187 non-null    float64
 14  WHO Region              187 non-null    object
dtypes: float64(4), int64(9), object(2)
memory usage: 22.0+ KB

In [14]:
covid=pd.read_csv("Dataset\covid_19_clean_complete.csv")

In [23]:
covid.head(50)

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,NaN,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,NaN,Albania,41.153300,20.168300,2020-01-22,0,0,0,0,Europe
2,NaN,Algeria,28.033900,1.659600,2020-01-22,0,0,0,0,Africa
3,NaN,Andorra,42.506300,1.521800,2020-01-22,0,0,0,0,Europe
4,NaN,Angola,-11.202700,17.873900,2020-01-22,0,0,0,0,Africa
5,NaN,Antigua and Barbuda,17.060800,-61.796400,2020-01-22,0,0,0,0,Americas
6,NaN,Argentina,-38.416100,-63.616700,2020-01-22,0,0,0,0,Americas
7,NaN,Armenia,40.069100,45.038200,2020-01-22,0,0,0,0,Europe
8,Australian Capital Territory,Australia,-35.473500,149.012400,2020-01-22,0,0,0,0,Western Pacific
9,New South Wales,Australia,-33.868800,151.209300,2020-01-22,0,0,0,0,Western Pacific
10,Northern Territory,Australia,-12.463400,130.845600,2020-01-22,0,0,0,0,Western Pacific
11,Queensland,Australia,-27.469800,153.025100,2020-01-22,0,0,0,0,Western Pacific
12,South Australia,Australia,-34.928500,138.600700,2020-01-22,0,0,0,0,Western Pacific
13,Tasmania,Australia,-42.882100,147.327200,2020-01-22,0,0,0,0,Western Pacific
14,Victoria,Australia,-37.813600,144.963100,2020-01-22,0,0,0,0,Western Pacific
15,Western Australia,Australia,-31.950500,115.860500,2020-01-22,0,0,0,0,Western Pacific
16,NaN,Austria,47.516200,14.550100,2020-01-22,0,0,0,0,Europe
17,NaN,Azerbaijan,40.143100,47.576900,2020-01-22,0,0,0,0,Europe
18,NaN,Bahamas,25.025885,-78.035889,2020-01-22,0,0,0,0,Americas
19,NaN,Bahrain,26.027500,50.550000,2020-01-22,0,0,0,0,Eastern Mediterranean
20,NaN,Bangladesh,23.685000,90.356300,2020-01-22,0,0,0,0,South-East Asia
21,NaN,Barbados,13.193900,-59.543200,2020-01-22,0,0,0,0,Americas
22,NaN,Belarus,53.709800,27.953400,2020-01-22,0,0,0,0,Europe
23,NaN,Belgium,50.833300,4.469936,2020-01-22,0,0,0,0,Europe
24,NaN,Benin,9.307700,2.315800,2020-01-22,0,0,0,0,Africa
25,NaN,Bhutan,27.514200,90.433600,2020-01-22,0,0,0,0,South-East Asia
26,NaN,Bolivia,-16.290200,-63.588700,2020-01-22,0,0,0,0,Americas
27,NaN,Bosnia and Herzegovina,43.915900,17.679100,2020-01-22,0,0,0,0,Europe
28,NaN,Brazil,-14.235000,-51.925300,2020-01-22,0,0,0,0,Americas
29,NaN,Brunei,4.535300,114.727700,2020-01-22,0,0,0,0,Western Pacific
30,NaN,Bulgaria,42.733900,25.485800,2020-01-22,0,0,0,0,Europe
31,NaN,Burkina Faso,12.238300,-1.561600,2020-01-22,0,0,0,0,Africa
32,NaN,Cabo Verde,16.538800,-23.041800,2020-01-22,0,0,0,0,Africa
33,NaN,Cambodia,11.550000,104.916700,2020-01-22,0,0,0,0,Western Pacific
34,NaN,Cameroon,3.848000,11.502100,2020-01-22,0,0,0,0,Africa
35,Alberta,Canada,53.933300,-116.576500,2020-01-22,0,0,0,0,Americas
36,British Columbia,Canada,53.726700,-127.647600,2020-01-22,0,0,0,0,Americas
37,Manitoba,Canada,53.760900,-98.813900,2020-01-22,0,0,0,0,Americas
38,New Brunswick,Canada,46.565300,-66.461900,2020-01-22,0,0,0,0,Americas
39,Newfoundland and Labrador,Canada,53.135500,-57.660400,2020-01-22,0,0,0,0,Americas
40,Nova Scotia,Canada,44.682000,-63.744300,2020-01-22,0,0,0,0,Americas
41,Ontario,Canada,51.253800,-85.323200,2020-01-22,0,0,0,0,Americas
42,Prince Edward Island,Canada,46.510700,-63.416800,2020-01-22,0,0,0,0,Americas
43,Quebec,Canada,52.939900,-73.549100,2020-01-22,0,0,0,0,Americas
44,Saskatchewan,Canada,52.939900,-106.450900,2020-01-22,0,0,0,0,Americas
45,NaN,Central African Republic,6.611100,20.939400,2020-01-22,0,0,0,0,Africa
46,NaN,Chad,15.454200,18.732200,2020-01-22,0,0,0,0,Africa
47,NaN,Chile,-35.675100,-71.543000,2020-01-22,0,0,0,0,Americas
48,Anhui,China,31.825700,117.226400,2020-01-22,1,0,0,1,Western Pacific
49,Beijing,China,40.182400,116.414200,2020-01-22,14,0,0,14,Western Pacific

In [17]:
covid.isnull().sum()

Province/State    34404
Country/Region        0
Lat                   0
Long                  0
Date                  0
Confirmed             0
Deaths                0
Recovered             0
Active                0
WHO Region            0
dtype: int64

In [18]:
covid.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49068 entries, 0 to 49067
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Province/State  14664 non-null  object
 1   Country/Region  49068 non-null  object
 2   Lat             49068 non-null  float64
 3   Long            49068 non-null  float64
 4   Date            49068 non-null  object
 5   Confirmed       49068 non-null  int64
 6   Deaths          49068 non-null  int64
 7   Recovered       49068 non-null  int64
 8   Active          49068 non-null  int64
 9   WHO Region      49068 non-null  object
dtypes: float64(2), int64(4), object(4)
memory usage: 3.7+ MB

In [21]:
covid["Province/State"].isnull().sum()

34404

In [24]:
covid["Province/State"].fillna(covid["Country/Region"], inplace=True)

In [25]:
covid["Province/State"].isnull().sum()

0

In [28]:
covid.isnull().sum()

Province/State    0
Country/Region    0
Lat               0
Long              0
Date              0
Confirmed         0
Deaths            0
Recovered         0
Active            0
WHO Region        0
dtype: int64

In [29]:
covid.head(50)

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,Afghanistan,Afghanistan,33.939110,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,Albania,Albania,41.153300,20.168300,2020-01-22,0,0,0,0,Europe
2,Algeria,Algeria,28.033900,1.659600,2020-01-22,0,0,0,0,Africa
3,Andorra,Andorra,42.506300,1.521800,2020-01-22,0,0,0,0,Europe
4,Angola,Angola,-11.202700,17.873900,2020-01-22,0,0,0,0,Africa
5,Antigua and Barbuda,Antigua and Barbuda,17.060800,-61.796400,2020-01-22,0,0,0,0,Americas
6,Argentina,Argentina,-38.416100,-63.616700,2020-01-22,0,0,0,0,Americas
7,Armenia,Armenia,40.069100,45.038200,2020-01-22,0,0,0,0,Europe
8,Australian Capital Territory,Australia,-35.473500,149.012400,2020-01-22,0,0,0,0,Western Pacific
9,New South Wales,Australia,-33.868800,151.209300,2020-01-22,0,0,0,0,Western Pacific
10,Northern Territory,Australia,-12.463400,130.845600,2020-01-22,0,0,0,0,Western Pacific
11,Queensland,Australia,-27.469800,153.025100,2020-01-22,0,0,0,0,Western Pacific
12,South Australia,Australia,-34.928500,138.600700,2020-01-22,0,0,0,0,Western Pacific
13,Tasmania,Australia,-42.882100,147.327200,2020-01-22,0,0,0,0,Western Pacific
14,Victoria,Australia,-37.813600,144.963100,2020-01-22,0,0,0,0,Western Pacific
15,Western Australia,Australia,-31.950500,115.860500,2020-01-22,0,0,0,0,Western Pacific
16,Austria,Austria,47.516200,14.550100,2020-01-22,0,0,0,0,Europe
17,Azerbaijan,Azerbaijan,40.143100,47.576900,2020-01-22,0,0,0,0,Europe
18,Bahamas,Bahamas,25.025885,-78.035889,2020-01-22,0,0,0,0,Americas
19,Bahrain,Bahrain,26.027500,50.550000,2020-01-22,0,0,0,0,Eastern Mediterranean
20,Bangladesh,Bangladesh,23.685000,90.356300,2020-01-22,0,0,0,0,South-East Asia
21,Barbados,Barbados,13.193900,-59.543200,2020-01-22,0,0,0,0,Americas
22,Belarus,Belarus,53.709800,27.953400,2020-01-22,0,0,0,0,Europe
23,Belgium,Belgium,50.833300,4.469936,2020-01-22,0,0,0,0,Europe
24,Benin,Benin,9.307700,2.315800,2020-01-22,0,0,0,0,Africa
25,Bhutan,Bhutan,27.514200,90.433600,2020-01-22,0,0,0,0,South-East Asia
26,Bolivia,Bolivia,-16.290200,-63.588700,2020-01-22,0,0,0,0,Americas
27,Bosnia and Herzegovina,Bosnia and Herzegovina,43.915900,17.679100,2020-01-22,0,0,0,0,Europe
28,Brazil,Brazil,-14.235000,-51.925300,2020-01-22,0,0,0,0,Americas
29,Brunei,Brunei,4.535300,114.727700,2020-01-22,0,0,0,0,Western Pacific
30,Bulgaria,Bulgaria,42.733900,25.485800,2020-01-22,0,0,0,0,Europe
31,Burkina Faso,Burkina Faso,12.238300,-1.561600,2020-01-22,0,0,0,0,Africa
32,Cabo Verde,Cabo Verde,16.538800,-23.041800,2020-01-22,0,0,0,0,Africa
33,Cambodia,Cambodia,11.550000,104.916700,2020-01-22,0,0,0,0,Western Pacific
34,Cameroon,Cameroon,3.848000,11.502100,2020-01-22,0,0,0,0,Africa
35,Alberta,Canada,53.933300,-116.576500,2020-01-22,0,0,0,0,Americas
36,British Columbia,Canada,53.726700,-127.647600,2020-01-22,0,0,0,0,Americas
37,Manitoba,Canada,53.760900,-98.813900,2020-01-22,0,0,0,0,Americas
38,New Brunswick,Canada,46.565300,-66.461900,2020-01-22,0,0,0,0,Americas
39,Newfoundland and Labrador,Canada,53.135500,-57.660400,2020-01-22,0,0,0,0,Americas
40,Nova Scotia,Canada,44.682000,-63.744300,2020-01-22,0,0,0,0,Americas
41,Ontario,Canada,51.253800,-85.323200,2020-01-22,0,0,0,0,Americas
42,Prince Edward Island,Canada,46.510700,-63.416800,2020-01-22,0,0,0,0,Americas
43,Quebec,Canada,52.939900,-73.549100,2020-01-22,0,0,0,0,Americas
44,Saskatchewan,Canada,52.939900,-106.450900,2020-01-22,0,0,0,0,Americas
45,Central African Republic,Central African Republic,6.611100,20.939400,2020-01-22,0,0,0,0,Africa
46,Chad,Chad,15.454200,18.732200,2020-01-22,0,0,0,0,Africa
47,Chile,Chile,-35.675100,-71.543000,2020-01-22,0,0,0,0,Americas
48,Anhui,China,31.825700,117.226400,2020-01-22,1,0,0,1,Western Pacific
49,Beijing,China,40.182400,116.414200,2020-01-22,14,0,0,14,Western Pacific

In [32]:
covid.to_csv("Country_wise_updated_data",index=False)

In [33]:
covid19=pd.read_csv("Country_wise_updated_data")

In [34]:
covid19.head()

,Province/State,Country/Region,Lat,Long,Date,Confirmed,Deaths,Recovered,Active,WHO Region
0,Afghanistan,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0,0,Eastern Mediterranean
1,Albania,Albania,41.15330,20.168300,2020-01-22,0,0,0,0,Europe
2,Algeria,Algeria,28.03390,1.659600,2020-01-22,0,0,0,0,Africa
3,Andorra,Andorra,42.50630,1.521800,2020-01-22,0,0,0,0,Europe
4,Angola,Angola,-11.20270,17.873900,2020-01-22,0,0,0,0,Africa

In [36]:
covid19.isnull().sum()

Province/State    0
Country/Region    0
Lat               0
Long              0
Date              0
Confirmed         0
Deaths            0
Recovered         0
Active            0
WHO Region        0
dtype: int64

In [38]:
covid19.to_excel("country_wise_updated_data.xlsx", index=False)

In [43]:
df=covid19[["Country/Region","Province/State","Confirmed","Deaths","Recovered","Active","WHO Region"]]

In [44]:
df.head(50)

,Country/Region,Province/State,Confirmed,Deaths,Recovered,Active,WHO Region
0,Afghanistan,Afghanistan,0,0,0,0,Eastern Mediterranean
1,Albania,Albania,0,0,0,0,Europe
2,Algeria,Algeria,0,0,0,0,Africa
3,Andorra,Andorra,0,0,0,0,Europe
4,Angola,Angola,0,0,0,0,Africa
5,Antigua and Barbuda,Antigua and Barbuda,0,0,0,0,Americas
6,Argentina,Argentina,0,0,0,0,Americas
7,Armenia,Armenia,0,0,0,0,Europe
8,Australia,Australian Capital Territory,0,0,0,0,Western Pacific
9,Australia,New South Wales,0,0,0,0,Western Pacific
10,Australia,Northern Territory,0,0,0,0,Western Pacific
11,Australia,Queensland,0,0,0,0,Western Pacific
12,Australia,South Australia,0,0,0,0,Western Pacific
13,Australia,Tasmania,0,0,0,0,Western Pacific
14,Australia,Victoria,0,0,0,0,Western Pacific
15,Australia,Western Australia,0,0,0,0,Western Pacific
16,Austria,Austria,0,0,0,0,Europe
17,Azerbaijan,Azerbaijan,0,0,0,0,Europe
18,Bahamas,Bahamas,0,0,0,0,Americas
19,Bahrain,Bahrain,0,0,0,0,Eastern Mediterranean
20,Bangladesh,Bangladesh,0,0,0,0,South-East Asia
21,Barbados,Barbados,0,0,0,0,Americas
22,Belarus,Belarus,0,0,0,0,Europe
23,Belgium,Belgium,0,0,0,0,Europe
24,Benin,Benin,0,0,0,0,Africa
25,Bhutan,Bhutan,0,0,0,0,South-East Asia
26,Bolivia,Bolivia,0,0,0,0,Americas
27,Bosnia and Herzegovina,Bosnia and Herzegovina,0,0,0,0,Europe
28,Brazil,Brazil,0,0,0,0,Americas
29,Brunei,Brunei,0,0,0,0,Western Pacific
30,Bulgaria,Bulgaria,0,0,0,0,Europe
31,Burkina Faso,Burkina Faso,0,0,0,0,Africa
32,Cabo Verde,Cabo Verde,0,0,0,0,Africa
33,Cambodia,Cambodia,0,0,0,0,Western Pacific
34,Cameroon,Cameroon,0,0,0,0,Africa
35,Canada,Alberta,0,0,0,0,Americas
36,Canada,British Columbia,0,0,0,0,Americas
37,Canada,Manitoba,0,0,0,0,Americas
38,Canada,New Brunswick,0,0,0,0,Americas
39,Canada,Newfoundland and Labrador,0,0,0,0,Americas
40,Canada,Nova Scotia,0,0,0,0,Americas
41,Canada,Ontario,0,0,0,0,Americas
42,Canada,Prince Edward Island,0,0,0,0,Americas
43,Canada,Quebec,0,0,0,0,Americas
44,Canada,Saskatchewan,0,0,0,0,Americas
45,Central African Republic,Central African Republic,0,0,0,0,Africa
46,Chad,Chad,0,0,0,0,Africa
47,Chile,Chile,0,0,0,0,Americas
48,China,Anhui,1,0,0,1,Western Pacific
49,China,Beijing,14,0,0,14,Western Pacific

In [46]:
df.isnull().sum()

Country/Region    0
Province/State    0
Confirmed         0
Deaths            0
Recovered         0
Active            0
WHO Region        0
dtype: int64

In [47]:
df.to_excel("Updated_data.xlsx", index=False)

In [51]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
49063    False
49064    False
49065     True
49066    False
49067     True
Length: 49068, dtype: bool